services:
  nlp-studies:
    image: nlp-studies:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nlp-studies-container
    volumes:
      # - E:\LocalPortfolio\PersonalProjects\nlp_studies\:/nlp_exp
      - C:\Users\icaro.zelioli.dev\Documents\Projects\nlp_studies\:/nlp_exp
    command: ["tail", "-f", "/dev/null"]
